name: Python CI

on:
  push:
    branches: [main]
    paths:
      - "python/**"
      - ".github/workflows/python-ci.yml"
      - "pyproject.toml"
      - ".python-version"
  pull_request:
    branches: [main]
    paths:
      - "python/**"
      - ".github/workflows/python-ci.yml"
      - "pyproject.toml"
      - ".python-version"

jobs:
  linting-checks:
    name: "Python linting checks"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"

      - name: Set up Python
        run: uv python install 3.12

      - name: Install dependencies
        run: uv sync --extra dev

      - name: Run isort
        run: uv run isort --check python/

      - name: Run black
        run: uv run black --check python/

      - name: Run flake8
        run: uv run flake8 python/

      - name: Run pylint
        run: uv run pylint python/**/*.py

  python-unit-tests:
    name: "Python unit tests"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"

      - name: Set up Python
        run: uv python install 3.12

      - name: Install dependencies
        run: |
          uv venv
          uv pip install -e .[test]

      - name: Run unit tests only
        run: uv run pytest python/tests/small/ -rs -vv
